apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ebay-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ebay-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ebay-frontend-service
            port:
              number: 80
